from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class RedisProtocol(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ex: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def keys(self, pattern: str) -> list[str]: ...
    async def publish(self, channel: str, message: str) -> None: ...
